### ISSUE TITLE
Can't connect DebugVars to the v2.0-rc.1 script

### ISSUE THREAD

**Issue by krasnovpro** [Lexikos/DebugVars.ahk#3] opened 2022-12-03 09:34 UTC
![image](https://user-images.githubusercontent.com/886676/205434228-1ff17665-dcc6-44f3-8118-20c89a6b3074.png)

**Comment by Lexikos** [comment] 2022-12-17 01:51
This is not a bug with DebugVars. The error is in the AutoHotkey process you are connecting to, as it shows in your screenshot. 

I'm fairly certain DebugVars was perfectly capable of attaching to scripts running on v2.0-rc.1, and whatever error you were getting is triggered by certain conditions in your script. For instance, it might have been triggered by a ComObject + ComObjConnect, which was a bug fixed by v1.1.36.01 and v2.0-rc.2, released several hours before you opened this Issue.

If you still get this issue with v2.0-rc.3, please post about it on the forums, with code that can be used to reproduce it.

**Closed as completed by Lexikos** 2022-12-17 01:51 UTC
